# Generated by Django 4.1.9 on 2023-07-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=2000)),
                ("price", models.FloatField()),
                ("image", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                ("rating", models.CharField(max_length=200)),
            ],
        ),
    ]
