# Generated by Django 4.1.9 on 2023-07-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="brand",
            field=models.CharField(default="Brand1", max_length=200),
            preserve_default=False,
        ),
    ]
